
:alpha		Alphabétique 
:category	Catégorie 
:common		Commune

:element_id_not_unique	D'autres élément de dialogue a déjà
Dialog_element_id = '# 1' 
:window_id_not_unique	La window_name '# 1' n'est pas unique à cette fenêtre pile.

:set_image_resource	Source de l'image ...  

:value		Valeur
:property	Attribut
:image_filtering	Image Filtering - Incremental
:module		Module
:colon		:
:filename	Nom de fichier
:image		Image

:set_plugin_resource	Define plugin / action 
:plugin_action_filtering	Plugin/Action Filtrage
:no_app_running		Applications non actif
:app	App
:plugin	Plugin
:action	Action

:set_logical_values	Set 'Selector' valeurs
