
:about_dialog_designer	Propos Dialog Designer ...

:prompt_2	 	Ajouter sous-menus / coulisses / séparateurs et boutons d'action buttons
:prompt_3		Ajouter un nouveau vitres, la traînée de commander à nouveau, cliquez sur pour sélectionner
:prompt_4		Ajouter des actions à gauche / droite / haut ou en bas des docks.
:prompt_5		Définissez producteurs et consommateurs de types de données. Cliquez avec le bouton droit d'ajouter ou de supprimer ou de modifier dataypes le panneau de droite directement.
:prompt_6		Voir les généré automatiquement le code XML et Magik. 
:prompt_7		Définissez les paramètres de module avant la génération du code.

:refresh_a		F5
:hide			Pas utilisé
:delete_element		Supprimer
:paste_element		Coller
:copy_element		Copie
:cut_element		Cut

:paste_element_tt_0	Coller (Ctrl+V)  [ #1 ]
:paste_element_tt_n	Coller (Ctrl+V)  [ #1 + #2 sub-elements]

:app	App :
:no_app_running	Applications non actif
:app_produced_data_types	App Data Types PRODUIT
:app_consumed_data_types	App Data Types COSOMMES
:dialog_produced_data_types	Dialog Data Types PRODUIT
:dialog_consumed_data_types	Dialog Data Types COSOMMES

:dialog_designer	Dialog Designer [ #1 ]
:new_dialog_class	dialog_class

:save_to_file		Enregisterer
:save_as		Enregisterer sous ...
:delete_dialog		Supprimer Dialog

:refresh_view		Rafraîchissement
:reinit			Re-Initialisation

:load_dialog_xml		Charge Dialog de XML
:load_from_file		Charge
:overwrite_existing_class?	L'importation de fichier sélectionné utilise la classe '# 1'.    

Voulez-vous remplacer le "# 1" conception de dialogue que vous avez déjà? 

Sinon, cliquez sur "Non" et utilisez le "Module Properties" de l'onglet pour changer la classe
'# 1' à autre chose. 

:save_dialog_xml		Enregistrer au format XML
:overwrite_existing_file?	Le fichier existe ... Écraser? 
:delete_current_dialog?	Supprimé dialogues ne peuvent pas être récupérés. 
 
Do you really want to delete this dialog design?   [ #1 ]
:new_dialog		Nouveau
:dialog_designer_help	... sur Dialog Designer
:dd_documentation		Documentation

:select_mode		Choisi / Drague / Modifier un élément du GUI ...
:no_dragging_into_self	Glisser-déplacer d'un élément en soi n'est pas valide.

:drop_click_prompt	Cliquez pour insérer élément du GUI ... 

:gui_layout		GUI Layout
:menubar			Menubar
:statusbar		Statusbar
:docks			Docks
:databus			Databus
:use_menubar		Menubar
:use_statusbar		Statusbar
:use_docks		Docks
:use_databus		Databus
:use_magik_xml		Magik / XML

:refresh_app_list		Refresh Application List
:xml			XML

:frame			Cadre

:insert_prompt		# 1: Cliquez intérieur d'une zone d'insérer mis en évidence ... <Space> pour revenir à "Sélectionner" Mode 
:select_prompt		Cliquez pour sélectionner le "#1"
:rowcol			Row Column Grid
:show_rowcol_cells	Show Row Column Grid?
:paned_window		Paned Window
:button_item		Command Button
:group_box		Group Box
:image_button_item	Image Button
:image_toggle_item	Image Toggle
:label_item		Label
:radio_group		Radio Group
:radio_item		Radio Button
:simple_list_item		Simple List
:text_choice_item	        	Text Choice
:text_item		Text Input
:text_window 		Text Window
:toggle_item		Check Box
:tabular_list		Tabular List
:tree_item		Tree List
:slider_item		Slider
:window_stack		Window Stack
:tab_box			Tab Box
:canvas			Canvas
:dd_paned_window		Paned Window
:dd_tab_box		Tab Box
:dd_group_box		Group Box
:dd_window_stack		Window Stack
:open_file_dir		File or Directory Selection
:style_choice_item	Style Choice
:plugin_item		Plugin or Action

:add_tab			Ajouter tab
:delete_tab		Supprimer l'onglet
:move_tab		Déplacer l'onglet move_tab (#1 / #2) à la position ...
:add_stack_window		Ajouter à pile 
:delete_stack_window	Supprimer cette fenêtre 

:add_menu		Ajouter Menu
:add_submenu		Ajouter Pullout Menu
:add_button		Ajouter Button
:add_separator		Ajouter Separator
:delete_menubar		Supprimer Menubar
:empty			Supprimer TOUTES les sous-catégories éléments ...
:view_xml		Voir XML ...

:dock_top		Top
:dock_bottom		Bottom
:dock_left		Gauche
:dock_right		Droit

:dock_section		Section
:dock_toolbar		Toolbar
:dock_action		Action

:add_section		New Section
:add_toolbar		New Toolbar
:add_action		Add Action

:add_to_list		Ajouter -->
:remove_from_list		<-- Supprimer

:dialog			     	Dialog
:dialog_class			Base Class
:dialog_class_default		default_class
:build				Module
:build_module			Constuir ...
:build_module_def			Attribut
:set_module_path			Path
:build_module_name	        	Nom/Version
:do_build_module			Construire Module
:build_module_description		Description
:build_module_requires		Requires
:build_module_name_default      	new_module_name    410
:build_module_description_default	Module Description?
:build_module_requires_default
:select_module_path		Sélectionner Module Path ...
:test			  	Test
:build_and_activate		Construire / Activer
:reactivate_dialog		Re-Activer
:alerts?				Afficher les alertes? 
:use_module_properties		Module Propriétés ...
:defined_modules			#1 of #2 définit les modules 
:defined_module_filter_label	Text filtre :
:defined_module_filter_tt		Combinaison de lettres pour filtrer la liste ci-dessous ...
:add_to_requires			<-- Ajouter
:remove_from_requires		X-- Retirer

:warning_used_dialog_class	Le dialogue Classe '# 1' n'est pas unique. 
:invalid_module_name_and_version    Invalide Nom / Version. 

:only_fixed_fonts_sizable	    Utiliser font_name='fixed' pour permettre à l'échelle police.

:supplimentary_gui_class_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####
####  SUPPLIMENTARY code for gui class '#3'
####    - add/redefine code here, it will not be auto-modified.

:add_status_pane	Add Pane
:delete_status_pane	Delete Pane
:delete_statusbar	Delete Statusbar

:code			Magik / XML
:explore_code		Explore generated code ...

:default_product_def
default_product layered_product

title
	Auto-generated default product (Dialog Designer)
end

:auto_generated_magik_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####

_package user


:auto_generated
	#### 
	####  Auto-generated by Dialog Designer : #1
:public_comments_init_actions|()|
##
##  Initialize actions for SELF.
##
:public_comments_build_gui|()|
##
##  Define the GUI layout.
##
:public_comments_quit|()|
##
##  Close the dialog.
##

:gui_action_definitions		
##
	## Work Area Actions ...
	##

:menubar_action_definitions		
##
	## Menubar Actions ...
	##

:toolbar_action_definitions		
##
	## Toolbar Actions ...
	##

:begin_loading_module_definition
####################################################################
## 
## Loading Module Definition (#1 @ #2) 
##
####################################################################
:end_loading
####################################################################
## 
## Module Load Complete.
##
####################################################################
:begin_loading_module
####################################################################
## 
## Loading Module (#1) 
##
####################################################################

:dd_colour_choice_tt	Colour
:dd_line_width_tt 	Line Width
:dd_dash_pattern_tt	Dash Pattern
:dd_line_join_style_tt	Join Style
:dd_line_end_style_tt	End Style
:dd_fill_percentage_tt	Fill Percentage
:dd_hatch_pattern_tt	Hatch Pattern
:dd_point_style_tt	Point Style

:pragma_topic_tt Code Rubrique (s): Entrez valeurs séparées par des virgules
:dialog_package	 Package
:missing_documentation_file
Documentation fichier non trouvé.

# 1

A été déplacé ou renommé ou supprimé.

:dialog_extra_slots Extra créneaux
:base_class_def Propriétés de la classe
:dialog_list Dialog liste

:dd_date_time_item Date Heure

:dialog_package_tt Entrez un nom de paquet (par défaut = user)
:dialog_method_list Méthode liste
:bad_word_launch
Documentation fichier ne peut pas être automatiquement ouvert.

# 1

Essayez de MS Word en premier, puis d'ouvrir le fichier à partir de là.

:pragma_usage_tt Code Usage (s): Sélectionnez ou entrez valeurs séparées par des virgules
:dialog_pragma Pragma
:dialog_class_list Classe liste
:unit_text_item Unité Text Input
:dialog_extra_slots_tt ... Ajouter virgule deliminated slot noms (c'est-à-extra_1, deux ,...)
:pragma_classify_level_tt	 Niveau de classification Code 
