
:alpha		Alphabetic
:category	Category
:common		Common

:element_id_not_unique	Some other dialog element already has 
dialog_element_id = '#1'
:window_id_not_unique	The window_name '#1' is not unique to this window stack.

:set_image_resource	Set image source ... 

:value		Value
:property	Property
:image_filtering	Image Filtering - Incremental
:module		Module
:colon		:
:filename	Filename
:image		Image

:set_plugin_resource	Set plugin / action 
:plugin_action_filtering	Plugin/Action Filtering
:no_app_running		No active Applications
:app			App
:plugin			Plugin
:action			Action

:set_logical_values	Set 'Selector' values
