
:alpha				Alphabetic
:category			Category
:common				Common

:element_id_not_unique	Some other dialog element already has 
dialog_element_id = '#1'
:window_id_not_unique		윈도우 '#1'는 윈도우 스텍에 유일하지 않슴니다.

:set_image_resource		이미지 설정 ... 

:value				값
:property			속성
:image_filtering		이미지 필터링 - Incremental
:module				모듈
:colon				:
:filename			파일이름
:image				이미지

:set_plugin_resource		Plusin/Action 설정 
:plugin_action_filtering	Plugin/Action 필터링
:no_app_running			활성된 프로그램이 없슴니다
:app				어플리케이션
:plugin				Plugin
:action				Action
