
:alpha		Alfabético 
:category	Categoría 
:common		Común 

:element_id_not_unique	Algún otro elemento del diálogo ya utiliza  
dialog_element_id = '#1'
:window_id_not_unique	El window_name '# 1' no es único para esta pila de ventanas.

:set_image_resource	Seleccionar imagen ... 

:value		Valor 
:property	Propiedad 
:image_filtering	Filtro - Incremental
:module		Módulo 
:colon		:
:filename	Nombre del archivo
:image		Imagen 

:set_plugin_resource	Seleccionar plugins / acción 
:plugin_action_filtering	Filtro Plugin/Acción
:no_app_running		Ninguna aplicación activa
:app	App
:plugin	Plugin
:action	Acción 

:set_logical_values	Añadir 'Selector' de valores
