
:about_dialog_designer	Acerca de Dialog Designer ...

:prompt_2	 	Añadir submenús/desplegables/separadores y botones de acción
:prompt_3		Añadir nuevos paneles, arrastar para establecer el orden, clic para seleccionar
:prompt_4		Añadir acciones a la izquierda/derecha/arriba o abajo.
:prompt_5		Seleccionar los productores y consumidores. Haga clic derecho para añadir/quitar o edita directamente en el panel derecho.
:prompt_6		Ver el XML y el código Magik generados automáticamente.
:prompt_7		Definir los parámetros del módulo antes de generar el código.

:refresh_a		F5
:hide			Ocultar
:delete_element		Eliminar
:paste_element		Pegar
:copy_element		Copiar
:cut_element		Cortar

:paste_element_tt_0	Pegar (Ctrl+V)  [ #1 ]
:paste_element_tt_n	Pegar (Ctrl+V)  [ #1 + #2 los elementos]

:app	App :
:no_app_running	Ninguna aplicación activa
:app_produced_data_types	PRODUCTORES de la Aplicación
:app_consumed_data_types	CONSUMIDORES de la Aplicación
:dialog_produced_data_types	PRODUCTORES del Diálogo
:dialog_consumed_data_types	CONSUMIDORES del Diálogo

:dialog_designer	Dialog Designer [ #1 ]
:new_dialog_class	dialog_class

:save_to_file		Guardar
:save_as		Guardar como ...
:delete_dialog		Borrar Diálogo

:refresh_view		Refrescar
:reinit			Reinicializar

:load_dialog_xml		Carga de diálogo desde XML
:load_from_file		Cargar desde archivo
:overwrite_existing_class?	El archivo seleccionado a importar utiliza la clase '# 1'. 

¿Quiere sobreescribir el diseño de diálogo '# 1' existente?

Si no es así, pulse 'No' y utilize la pestaña 'Propiedades del Módulo' para cambiar la clase
'#1'. 

:save_dialog_xml		Guardar el diálogo como XML
:overwrite_existing_file?	El archivo ya existe ... Sobreescribirlo?
:delete_current_dialog?	Los diálogos borrados no se pueden recuperar.
 
¿Está seguro de que desea borrar este diseño de diálogo? [# 1] 
:new_dialog		Nuevo
:dialog_designer_help	... sobre Dialog Designer
:dd_documentation		Documentación 

:select_mode		Seleccionar / Arrastrar / Editar un elemento ... 
:no_dragging_into_self	Arrastrar un elemento sobre sí mismo no es válido. 

:drop_click_prompt	Haga clic para insertar un elemento ... 

:gui_layout		Diseño GUI
:menubar			Menús 
:statusbar		Barra de estado
:docks			Docks
:databus			Databus
:use_menubar		Barra de Menú
:use_statusbar		Barra de estado
:use_docks		Docks
:use_databus		Databus
:use_magik_xml		Magik / XML

:refresh_app_list		Refrescar la lista de aplicaciones
:xml			XML

:frame			Frame

:insert_prompt		#1: Haga clic en el interior de un área resaltada para insertar ... <Space> para volver al modo 'Seleccionar'
:select_prompt		Haga clic para seleccionar el '# 1'
:rowcol			Row Column Grid
:show_rowcol_cells	¿Mostrar Row Column Grid?
:paned_window		Paned Window
:button_item		Command Button
:group_box		Group Box
:image_button_item	Image Button
:image_toggle_item	Image Toggle
:label_item		Label
:radio_group		Radio Group
:radio_item		Radio Button
:simple_list_item		Simple List
:text_choice_item	        	Text Choice
:text_item		Text Input
:text_window 		Text Window
:toggle_item		Check Box
:tabular_list		Tabular List
:tree_item		Tree List
:slider_item		Slider
:window_stack		Window Stack
:tab_box			Tab Box
:canvas			Canvas
:dd_paned_window		Paned Window
:dd_tab_box		Tab Box
:dd_group_box		Grupo Box
:dd_window_stack		Window Stack
:open_file_dir		File or Directory Selection 
:style_choice_item	Style Choice 
:plugin_item		Plugin or Action

:add_tab			Añadir pestaña 
:delete_tab		Eliminar pestaña actual
:move_tab		Mover pestaña actual (# 1 / # 2) a la posición ...
:add_stack_window		Añadir la ventana a la pila 
:delete_stack_window	Eliminar la ventana de la pila

:add_menu		Añadir Menú
:add_submenu		Añadir Menú desplegable 
:add_button		Añadir Botón 
:add_separator		Añadir Separador 
:delete_menubar		Eliminar Barra de menú
:empty			Eliminar TODOS los elementos ... 
:view_xml		Ver XML ...

:dock_top		Superior
:dock_bottom		Inferior
:dock_left		Izquierda 
:dock_right		Derecho 

:dock_section		Sección 
:dock_toolbar		Barra de herramientas
:dock_action		Acción 

:add_section		Nueva Sección
:add_toolbar		Nueva barra de herramientas 
:add_action		Añadir Acción 

:add_to_list		Añadir a la lista --> 
:remove_from_list		<-- Eliminar de la lista

:dialog			     	Diálogo 
:dialog_class			Clase Base
:dialog_class_default		default_class
:build				Módulo
:build_module			Build ...
:build_module_def			Propiedades 
:set_module_path			Directorio
:build_module_name	        	Nombre/Versión 
:do_build_module			Build Módulo
:build_module_description		Descripción
:build_module_requires		Requiere 
:build_module_name_default      	new_module_name    410
:build_module_description_default	¿Descripción del Módulo? 
:build_module_requires_default
:select_module_path		Seleccione el directorio ...
:test			  	Test 
:build_and_activate		Build / Activar
:reactivate_dialog		Reactivar 
:alerts?				¿Mostrar alertas? 
:use_module_properties		Propiedades del módulo ... 
:defined_modules			#1 de #2 módulos definidos 
:defined_module_filter_label	filtro: 
:defined_module_filter_tt		Escriba para filtrar lista de abajo ...
:add_to_requires			<-- Añadir 
:remove_from_requires		X-- Eliminar 

:warning_used_dialog_class	El diálogo de la clase '# 1' no es única.
:invalid_module_name_and_version    Nombre/Versión inválidos. 

:bad_word_launch
El archivo de documentación no puede ser abierto automáticamente. 

#1

Iniciar MS Word y, a continuación, abra el archivo desde allí.

:missing_documentation_file
No se encuentra el archivo de documentación.

#1

ha sido movido, renombrado o borrado. 

:only_fixed_fonts_sizable	    Use font_name ='fixed' para permitir cambiar el tamaño fuente.


:supplimentary_gui_class_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####
####  SUPPLIMENTARY code for gui class '#3'
####    - add/redefine code here, it will not be auto-modified.

:add_status_pane	Añadir Pane 
:delete_status_pane	Eliminar Pane
:delete_statusbar	Eliminar de estado 

:code			Magik / XML
:explore_code		Explora código generado ...

:default_product_def
default_product layered_product

title
	Auto-generated default product (Dialog Designer)
end

:auto_generated_magik_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####

_package user


:auto_generated
	#### 
	####  Auto-generated by Dialog Designer : #1
:public_comments_init_actions|()|
##
##  Initialize actions for SELF.
##
:public_comments_build_gui|()|
##
##  Define the GUI layout.
##
:public_comments_quit|()|
##
##  Close the dialog.
##

:gui_action_definitions		
##
	## Work Area Actions ...
	##

:menubar_action_definitions		
##
	## Menubar Actions ...
	##

:toolbar_action_definitions		
##
	## Toolbar Actions ...
	##

:begin_loading_module_definition
####################################################################
## 
## Loading Module Definition (#1 @ #2) 
##
####################################################################
:end_loading
####################################################################
## 
## Module Load Complete.
##
####################################################################
:begin_loading_module
####################################################################
## 
## Loading Module (#1) 
##
####################################################################

:dd_colour_choice_tt	Colour
:dd_line_width_tt 	Line Width
:dd_dash_pattern_tt	Dash Pattern
:dd_line_join_style_tt	Join Style
:dd_line_end_style_tt	End Style
:dd_fill_percentage_tt	Fill Percentage
:dd_hatch_pattern_tt	Hatch Pattern
:dd_point_style_tt	Point Style

:dialog_package			Paquete
:dialog_package_tt		Introduce un nombre para el paquete (por defecto = user)
:dialog_extra_slots		Extra slots
:dialog_extra_slots_tt		... Añade los nombres de los slots separados por comas (p.ej. extra_1,two,...)

:dialog_pragma			Pragma 
:pragma_classify_level_tt		Nivel de clasificación del código
:pragma_topic_tt			Tópico(s) del Código: Introduce valores separados por comas
:pragma_usage_tt			Uso(s) del Código: Selecciona o introduce valores separados por comas

:dialog_class_list	Lista de Clases
:dialog_method_list	Lista de Métodos
:dialog_list		Lista de Diálogos

:base_class_def			Propiedades de la Clase

:dd_date_time_item	Date Time
:unit_text_item		Unit Text Input
