
:alpha		Alphabetisch
:category	Kategory
:common		Normal

:element_id_not_unique	Ein anderes Dialogelement hat schon 
dialog_element_id = '#1'
:window_id_not_unique	window_name '#1' ist mehrmals vorhanden.

:set_image_resource	Bild auswählen ... 

:property	Eigenschaft
:value		Wert

:colon			:
:module			Modul	
:filename		Dateiname
:image			Bild
:image_filtering	Bild filtern - inkrementell

:set_plugin_resource	Setze Plugin / Aktion 
:plugin_action_filtering	Plugin / Aktion filtern
:no_app_running		Keine aktive Applikation
:app	Applikation
:plugin	Plugin
:action	Aktion

:set_logical_values	Auswahlwerte festlegen