
:about_dialog_designer	Über Dialog Designer ...

:prompt_2	 	Füge Untermenüs/Pullouts/Separatoren und actionable buttons
:prompt_3		Füge neue Panes hinzu, ziehen zum Neuordnen, klicken zum Auswählen
:prompt_4		Füge Knopfaktionen zu den linken/rechten/oberen oder unteren Docks hinzu.
:prompt_5		Setze Datentypen für Produzenten und Konsumenten.  Rechtsklick zum Hinzufügen/Entfernen der Datentypen oder zum direkten Verändern des rechten Panels.
:prompt_6		Den automatisch generierten XML und Magik Code ansehen.
:prompt_7		Setzen Sie die Modulparameter vor der Codegenerierung.

:refresh_a		F5
:hide			Nicht benutzen
:delete_element		Löschen
:paste_element		Einfügen
:copy_element		Kopieren
:cut_element		Ausschneiden

:paste_element_tt_0	Einfügen (Ctrl+V)  [ #1 ]
:paste_element_tt_n	Einfügen (Ctrl+V)  [ #1 + #2 Unterelemente]


:dialog_designer	Dialog Designer [ #1 ]
:new_dialog_class	dialog_class

:save_to_file		Speichern
:save_as		Speichern unter ...
:delete_dialog		Dialog Löschen

:refresh_view		Neuaufbau
:reinit			Reinitialisieren

:dialog_class_list	Liste der Klassen
:dialog_method_list	Liste der Methoden
:dialog_list		Liste der Dialoge

:app			Applikation :
:app_produced_data_types	Produzierte Datentypen d. Applikation
:app_consumed_data_types	Konsumierte Datentypen d. Applikation
:dialog_consumed_data_types	KONSUMIERTE Datentypen d. Dialogs
:dialog_produced_data_types	PRODUZIERTE Datentypen d. Dialogs
:no_app_running			Keine Applikation gestartet ...

:load_dialog_xml		Lade Dialog von XML
:load_from_file		Öffnen
:overwrite_existing_class?	Die ausgewählte Importdatei benutzt die Klasse '#1'.   

Wollen Sie das Dialogdesign '#1' überschreiben, das Sie schon benutzen?

Wenn nicht, drücken Sie "Nein" und benutzen Sie den Tab 'Modul Eigenschaften', um die Klasse #1 
zu einer anderen zu ändern.

:save_dialog_xml		Speichere Dialog als XML
:overwrite_existing_file?	Datei existiert schon ... überschreiben?
:delete_current_dialog?		Gelöschte Dialoge können nicht wieder hergestellt werden. 
 
Wollen Sie dieses Dialogdesign [ #1 ] wirklich löschen?
:new_dialog		Neu
:dialog_designer_help	... über Dialog Designer
:dd_documentation		Dokumentation

:select_mode		Auswählen / Platzieren / Editieren eines GUI-Elements ... 
:no_dragging_into_self	Ein Element kann nicht in sich selbst platziert werden.

:drop_click_prompt	Klicken um ein GUI-Element einzufügen...

:gui_layout		GUI Layout
:menubar			Menuleiste
:statusbar		Statusleiste
:docks			Docks
:databus			Databus
:use_menubar		Menuleiste
:use_statusbar		Statusleiste
:use_docks		Docks
:use_databus		Databus
:use_magik_xml		Magik / XML

:refresh_app_list	Applicationsliste neu aufbauen
:xml			XML

:frame			Frame

:insert_prompt		#1 : Klicken Sie in eine hervorgehobene Fläche zum Einfügen ... <Space> um in den Auswahlmodus zurückzukehren.
:select_prompt		Klicken um '#1' auszuwählen
:rowcol			Row Column Grid
:show_rowcol_cells	Row Column Grid anzeigen?
:paned_window		Paned Window
:button_item		Command Button
:group_box		Group Box
:image_button_item	Image Button
:image_toggle_item	Image Toggle
:label_item		Label
:radio_group		Radio Group
:radio_item		Radio Button
:simple_list_item		Simple List
:text_choice_item	        	Text Choice
:text_item		Textfeld
:text_window 		Textfenster
:toggle_item		Check Box
:tabular_list		Tablular List
:tree_item		Tree List
:slider_item		Slider
:window_stack		Window Stack
:tab_box			Tab Box
:canvas			Canvas
:dd_paned_window		Paned Window
:dd_tab_box		Tab Box
:dd_group_box		Group Box
:dd_window_stack		Window Stack
:open_file_dir		Datei- oder Verzeichnisauswahl
:style_choice_item	Style-Auswahl
:plugin_item		Plugin oder Aktion

:add_tab		Tab hinzufügen
:delete_tab		Aktuellen Tab löschen
:move_tab		Aktuellen Tab (#1/#2) verschieben auf Position ...
:add_stack_window		Fenster zum stack hinzufügen
:delete_stack_window	Dieses stacked window löschen

:add_menu		Menü hinzufügen
:add_submenu		Untermenü hinzufügen
:add_button		Knopf hinzufügen
:add_separator		Separator hinzufügen
:delete_menubar		Menüleiste löschen
:empty			ALLE Unterelemente anschauen ...
:view_xml		XML anschauen...

:dock_top		top
:dock_bottom		bottom
:dock_left		left
:dock_right		right

:dock_section		Sektion
:dock_toolbar		Werkzeugleiste
:dock_action		Aktion

:add_section		Neue Sektion
:add_toolbar		Neue werkzeugleiste
:add_action		Aktion hinzufügen

:add_to_list		Der Liste hinzufügen -->
:remove_from_list		<-- Aus Liste entfernen

:dialog			     	Dialog
:dialog_class			Basisklasse
:dialog_class_default		default_class
:build				Modul
:build_module			Erstellen ...
:build_module_def			Eigenschaften
:set_module_path			Pfad
:build_module_name	        	Name/Version
:do_build_module			Modul Erstellen
:build_module_description		Beschreiben
:build_module_requires		Benötigt
:build_module_name_default      	new_module_name    410
:build_module_description_default	Modul Beschreibung?
:build_module_requires_default
:test			  	Test
:build_and_activate		Erstellen / Aktivieren
:reactivate_dialog		Reaktivieren
:alerts?				Warnungen Anzeigen?
:use_module_properties		Modul Eigenschaften ...
:defined_modules			#1 von #2 definierten Modulen
:defined_module_filter_label	Textfilter :
:defined_module_filter_tt	Geben Sie Zeichen ein, um die Liste zu filtern ...
:add_to_requires			<-- Hinzufügen
:remove_from_requires		X-- Entfernen

:warning_used_dialog_class	The Dialog Class '#1' is not unique.
:invalid_module_name_and_version    Ungültiger Name/Version.

:only_fixed_fonts_sizable	    Use font_name='fixed' to allow font scaling.

:add_status_pane	Pane hinzufügen
:delete_status_pane	Pane löschen
:delete_statusbar	Statusleiste löschen

:code			Magik / XML
:explore_code		Generierten Code untersuchen ...

:default_product_def
default_product layered_product

title
	Auto-generated default product (Dialog Designer)
end

:auto_generated_magik_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####

_package user


:auto_generated
	#### 
	####  Auto-generated by Dialog Designer : #1
:public_comments_init_actions|()|
##
##  Initialize actions for SELF.
##
:public_comments_build_gui|()|
##
##  Define the GUI layout.
##
:public_comments_quit|()|
##
##  Close the dialog.
##

:gui_action_definitions		
##
	## Work Area Actions ...
	##

:menubar_action_definitions		
##
	## Menubar Actions ...
	##

:toolbar_action_definitions		
##
	## Toolbar Actions ...
	##

:begin_loading_module_definition
####################################################################
## 
## Loading Module Definition (#1 @ #2) 
##
####################################################################
:end_loading
####################################################################
## 
## Module Load Complete.
##
####################################################################
:begin_loading_module
####################################################################
## 
## Loading Module (#1) 
##
####################################################################

:dd_colour_choice_tt	Farbe
:dd_line_width_tt 	Linienbreite
:dd_dash_pattern_tt	Strichmuster
:dd_line_join_style_tt	Join Style
:dd_line_end_style_tt	End Style
:dd_fill_percentage_tt	Füllung %
:dd_hatch_pattern_tt	Füllmuster
:dd_point_style_tt	Punkt Style

:pragma_topic_tt			Code Topic(s): Geben Sie durch Kommata getrennte Werte ein.
:dialog_package			Package
:missing_documentation_file	
Dokumentation nicht gefunden.

#1

wurde umbenannt, verschoben oder gelöscht.

:dialog_extra_slots		Extraslots
:base_class_def			Klasseneigenschaften
:dd_date_time_item	Datum/Zeit

:dialog_package_tt		Geben Sie eine Pacakgedefinition ein (Standard = user)
:select_module_path		Select Module Path ...
:bad_word_launch			
Dokumentation kann nicht automatisch geöffnet werden.

#1

Versuchen Sie, zuerst MS Word zu starten und anschließend die Datei damit zu öffnen.

:supplimentary_gui_class_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####
####  SUPPLIMENTARY code for gui class '#3'
####    - add/redefine code here, it will not be auto-modified.

:pragma_usage_tt			Code Usage(s): Geben Sie durch Kommata getrennte Werte ein.
:dialog_pragma			Pragma 
:unit_text_item		Einheitentextfeld
:dialog_extra_slots_tt		... fügen Sie durch Kommata getrennte Slot-Namen hinzu (z.B. extra_1,two,...)
:pragma_classify_level_tt		Code Level Klassifizierung