
:alpha		Alfabético
:category	Category
:common		Comum

:element_id_not_unique	Alguns outros diálogo elemento já possui
dialog_element_id = '#1'
:window_id_not_unique	O window_name '# 1' não é exclusivo para esta janela pilha.


:set_image_resource	Set imagem fonte ...

:value		Value
:property	Propriedade 
:image_filtering	Image Filtering - Incremental
:module		Módulo 
:colon		:
:filename	Filename
:image		Imagem

:set_plugin_resource	Set plugins / acção 
:plugin_action_filtering	Plugin / Action Filtering 
:no_app_running		No activa Applications 
:app	App
:plugin	Plugin
:action	Acção 

:set_logical_values	Set 'Selector' valores
