
:about_dialog_designer	About Dialog Designer ...

:prompt_2	 	Adicionar submenus / pullouts / separadores e ações botões
:prompt_3		Adicionar novos painéis, arrastar para re - forma, clique para selecionar
:prompt_4		Botão adicionar ações para a esquerda / direita / superior ou inferior docas.
:prompt_5		Set Produtor Consumidor e tipos de dados. Clique com o botão direito para adicionar / remover dataypes ou editar o direito painel diretamente.
:prompt_6		View gerado automaticamente o código XML e Magik. 
:prompt_7		Definir o módulo parâmetros antes de gerar o código.

:refresh_a		F5
:hide			Não utilize 
:delete_element		Delete
:paste_element		Colar
:copy_element		Copy
:cut_element		Cut

:paste_element_tt_0	Paste (Ctrl+V)  [ #1 ]
:paste_element_tt_n	Paste (Ctrl+V)  [ #1 + #2 submarino - elementos]

:app	App :
:no_app_running	No activa Applications 
:app_produced_data_types	App PRODUZIDOS Data Types
:app_consumed_data_types	App CONSUMED Data Types
:dialog_produced_data_types	Dialog PRODUZIDOS Data Types
:dialog_consumed_data_types	Dialog CONSUMED Data Types

:dialog_designer	Dialog Designer [ #1 ]
:new_dialog_class	dialog_class

:save_to_file		Save
:save_as		Salvar como ... 
:delete_dialog		Delete Dialog

:refresh_view		Refresh
:reinit			Re-Initialise

:load_dialog_xml		Load Dialog de XML ???
:load_from_file		Open ???
:overwrite_existing_class?	O arquivo selecionado importação utiliza a classe '#1'.

Você deseja substituir o 'número 1' diálogo concepção você já tem?

Se não estiver, pressione 'Não' e use o "Módulo Properties' para alterar a classe
'#1' para qualquer coisa. 

:save_dialog_xml		Save Dialog como XML ???
:overwrite_existing_file?	O arquivo já existe ... Sobrescrever? 
:delete_current_dialog?	Excluído diálogos não podem ser recuperados.
 
Você realmente deseja excluir este diálogo desenho? [# 1] 
:new_dialog		New 
:dialog_designer_help	... sobre Dialog Designer
:dd_documentation		Documentation

:select_mode		Select / Drag / Editar uma GUI elemento ... 
:no_dragging_into_self	Arrastando um elemento em si mesmo não é válido. 

:drop_click_prompt	Clique para inserir elemento gui ... 

:gui_layout		GUI Layout
:menubar			Menubar
:statusbar		Statusbar
:docks			Docks
:databus			Databus
:use_menubar		Menubar
:use_statusbar		Statusbar
:use_docks		Doca
:use_databus		Databus
:use_magik_xml		Magik / XML

:refresh_app_list		Refresh Application List
:xml			XML

:frame			Moldura

:insert_prompt		#1: Clique no interior de uma área destacada para inserir ... <Space> para voltar ao 'Select' Modo 
:select_prompt		Clique para selecionar o '#1'
:rowcol			Row Column Grid
:show_rowcol_cells	Show Row Column Grid?
:paned_window		Paned Window
:button_item		Command Button
:group_box		Group Box
:image_button_item	Image Button
:image_toggle_item	Image Toggle
:label_item		Label
:radio_group		Radio Group
:radio_item		Radio Button
:simple_list_item		Simple List
:text_choice_item	        	Text Choice
:text_item		Text Input
:text_window 		Text Window
:toggle_item		Check Box
:tabular_list		Tabular List
:tree_item		Tree List
:slider_item		Slider
:window_stack		Window Stack
:tab_box			Tab Box
:canvas			Canvas
:dd_paned_window		Paned Window
:dd_tab_box		Tab Box
:dd_group_box		Group Box
:dd_window_stack		Window Stack
:open_file_dir		Arquivo ou diretório Selection 
:style_choice_item	Style Choice
:plugin_item		Plugin ou Action

:add_tab			Guia Adicionar 
:delete_tab		Delete atual guia 
:move_tab		Move atual guia (# 1 / # 2), a posição ... 
:add_stack_window		Add janela para empilhar 
:delete_stack_window	Excluir esta janela empilhadas 

:add_menu		Adicionar Menu
:add_submenu		Adicionar Pullout Menu
:add_button		Adicionar Button
:add_separator		Adicionar Separator
:delete_menubar		Delete Menubar
:empty			Delete ALL sub-elements ...
:view_xml		View XML ...

:dock_top		Top
:dock_bottom		Bottom
:dock_left		Esquerda 
:dock_right		Right

:dock_section		Secção 
:dock_toolbar		Toolbar
:dock_action		Action

:add_section		Nova Seção
:add_toolbar		New Toolbar
:add_action		Adicionar Action

:add_to_list		Adicionar a lista --> 
:remove_from_list		<-- Remover da lista

:dialog			     	Dialog
:dialog_class			Base Class
:dialog_class_default		default_class
:build				Module
:build_module			Build ...
:build_module_def			Properties
:set_module_path			Path
:build_module_name	        	Nome / Versão 
:do_build_module			Build Module
:build_module_description		Descrição 
:build_module_requires		Requires
:build_module_name_default      	new_module_name    410
:build_module_description_default	Módulo Descrição? 
:build_module_requires_default
:select_module_path		Select Module Path ...
:test			  	Ensaio 
:build_and_activate		Build / Activar 
:reactivate_dialog		Re-Activate
:alerts?				Show Alertas? 
:use_module_properties		Module Properties ...
:defined_modules			#1 da #2 definida módulos 
:defined_module_filter_label	texto filtro: 
:defined_module_filter_tt		Tipo carta combinação para filtrar lista abaixo ... 
:add_to_requires			<-- Adicionar
:remove_from_requires		X-- Remove ???

:warning_used_dialog_class	O Dialog Class' # 1 'não é exclusivo. 
:invalid_module_name_and_version    Invalide Nome / Versão. 

:bad_word_launch
Documentação arquivo não pode ser auto - aberto.

#1

Tente começando MS Word em primeiro lugar, depois abrir o arquivo de lá.

:missing_documentation_file
Documentação arquivo não encontrado.

# 1

Foi movida / renomeados ou excluídos.

:only_fixed_fonts_sizable	    Use font_name = 'fixo' para permitir fonte escamação. 

:supplimentary_gui_class_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####
####  SUPPLIMENTARY code for gui class '#3'
####    - add/redefine code here, it will not be auto-modified.

:add_status_pane	Adicionar Pane
:delete_status_pane	Delete Pane
:delete_statusbar	Delete Statusbar

:code			Magik / XML
:explore_code		Explore código gerado ...

:default_product_def
default_product layered_product

title
	Auto-generated default product (Dialog Designer)
end

:auto_generated_magik_file_header
##% text_encoding = iso8859_1
#### 
####  Auto-generated by Dialog Designer ( #1 )
####
####  System.user_mame = #2
####

_package user


:auto_generated
	#### 
	####  Auto-generated by Dialog Designer : #1
:public_comments_init_actions|()|
##
##  Initialize actions for SELF.
##
:public_comments_build_gui|()|
##
##  Define the GUI layout.
##
:public_comments_quit|()|
##
##  Close the dialog.
##

:gui_action_definitions		
##
	## Work Area Actions ...
	##

:menubar_action_definitions		
##
	## Menubar Actions ...
	##

:toolbar_action_definitions		
##
	## Toolbar Actions ...
	##

:begin_loading_module_definition
####################################################################
## 
## Loading Module Definition (#1 @ #2) 
##
####################################################################
:end_loading
####################################################################
## 
## Module Load Complete.
##
####################################################################
:begin_loading_module
####################################################################
## 
## Loading Module (#1) 
##
####################################################################

:dd_colour_choice_tt	Colour
:dd_line_width_tt 	Line Width
:dd_dash_pattern_tt	Dash Pattern
:dd_line_join_style_tt	Join Style
:dd_line_end_style_tt	End Style
:dd_fill_percentage_tt	Fill Percentage
:dd_hatch_pattern_tt	Hatch Pattern
:dd_point_style_tt	Point Style

:pragma_topic_tt Código Tópico (s): Digite valores separados por vírgula
:dialog_package Package
:dialog_extra_slots Extra slots
:base_class_def Class Properties
:dialog_list Dialog lista

:dd_date_time_item Data Hora

:dialog_package_tt Digite um pacote nome (default = user)
:tabular_list tabulares List
:dialog_method_list Método lista
:pragma_usage_tt Código de Uso (s): Seleccione ou introduza valores separados por vírgula
:dialog_pragma Pragma
:dialog_class_list Classe lista
:unit_text_item Unidade Text Input
:dialog_extra_slots_tt ... Adicionar vírgula deliminated slot nomes (ou seja extra_1, dois ,...)
:pragma_classify_level_tt Código Nível classificação
